gades_proj:
  outputs:
    dev:
      dataset: dbt_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/dbt/keys/gcp-key.json
      location: europe-southwest1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 6
      type: bigquery
  target: dev
